# Generated by Django 5.2.7 on 2025-10-16 23:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1400)])),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('autor', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidiaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1400)])),
                ('estoque', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1400)])),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('edicao', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateField(default=django.utils.timezone.now)),
                ('devolvido_em', models.DateField(blank=True, null=True)),
                ('item_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
